[build]
  command = """
  echo "Using environment variables for build..."
  export VITE_WEATHER_API_KEY=$VITE_WEATHER_API_KEY
  export VITE_SPOTIFY_CLIENT_ID=$VITE_SPOTIFY_CLIENT_ID
  export VITE_SPOTIFY_CLIENT_SECRET=$VITE_SPOTIFY_CLIENT_SECRET
  export VITE_SPOTIFY_REFRESH_TOKEN=$VITE_SPOTIFY_REFRESH_TOKEN
  export VITE_APPLE_TEAM_ID=$VITE_APPLE_TEAM_ID
  export VITE_APPLE_KEY_ID=$VITE_APPLE_KEY_ID
  export VITE_APPLE_PRIVATE_KEY=$VITE_APPLE_PRIVATE_KEY
  
  npm run build
  """
  functions = "functions"
  publish = "dist"
